version: '3.8'

services:
  system-mongo-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<secure_password>
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27018:27017
    expose:
      - 27018

  system-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: <username>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <secure_password>
      ME_CONFIG_MONGODB_URL: mongodb://<username>:<secure_password>@system-mongo-db:27017
