version: '3.8'

services:
  system-mongo-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongokyle
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27018:27017
    expose:
      - 27018

  system-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongokyle
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongokyle:password@system-mongo-db:27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
